"""add link ownership

Revision ID: 40899879b5a5
Revises: 2da3212787b4
Create Date: 2026-02-03 09:49:16.981249

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40899879b5a5"
down_revision: Union[str, Sequence[str], None] = "2da3212787b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("links", sa.Column("owner_api_key_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_links_owner_api_key_id"), "links", ["owner_api_key_id"], unique=False)
    op.create_foreign_key(
        None, "links", "api_keys", ["owner_api_key_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "links", type_="foreignkey")
    op.drop_index(op.f("ix_links_owner_api_key_id"), table_name="links")
    op.drop_column("links", "owner_api_key_id")
    # ### end Alembic commands ###
